angular_momentum_aux_mask_id: .inf
angular_momentum_loss_weight: 0.1
block_size: 999
experiment_name: next_token_hamiltonian_aux
force_aux_dataset: two_body
hamiltonian_aux_mask_id: .inf
hamiltonian_loss_weight: 0.1
input_dim: 2
input_vocab_size: 7003
mask_id: 7000
num_data_points: 1000
output_dim: 2
output_vocab_size: 7003
predict_type: next_token
use_angular_momentum_aux_loss: true
use_force_aux_loss: false
use_force_law_loss: false
use_hamiltonian_aux_loss: true
